version: "3"
services:
  iambic:
    environment:
      - IAMBIC_CONFIG=arn:aws:secretsmanager:us-west-2:759357822767:secret:dev/iambic-full
      - AWS_PROFILE=arn:aws:iam::940552945933:role/NoqCentralRoleCorpNoqDev
      - IAMBIC_CONFIG_ASSUME_ROLE=arn:aws:iam::759357822767:role/development_admin
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    build:
      context: .
      dockerfile: Dockerfile.awslambdaric
    image: iambic
    ports:
      - 9000:8080
      - 56780:5678
    volumes:
      - ~/.aws:/root/.aws:cached
      - .:/app:cached
    entrypoint:
      - "/usr/bin/aws-lambda-rie"
      - "/usr/bin/python"
      - "-m"
      - "debugpy"
      - "--listen"
      - "0.0.0.0:5678"
      - "--wait-for-client"
      - "-m"
      - "awslambdaric"
    command: "iambic.lambda.app.handler"
