name: Run Iambic Expire
on:
  workflow_dispatch:
  schedule:
    - cron:  '5 * * * *' # every every hour at minute 5


jobs:
  iambic-expire:
    runs-on: self-hosted
    environment: production
    if: github.ref == 'refs/heads/main'
    name: Check expire resources
    timeout-minutes: 30 # If periodic expires takes more than 30min to run, we probably have performance issue
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      id-token: write
      contents: read
    steps:
      - name: trigger_workflow
        id: trigger_workflow
        run: |
          echo "trigger workflow"
