name: Run Iambic Apply when someone comments on PR
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  iambic-apply:
    runs-on: self-hosted
    if: ${{ github.event.issue.pull_request && (github.event.comment.body == 'iambic git-apply') }}
    name: Run Iambic Git-Apply when someone comments on PR
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Dump GitHub context
        id: github_context_step
        if: ${{ false }}
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        if: ${{ !env.ACT }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: __TEMPLATE_IAMBIC_ASSUME_ROLE_ARN
          aws-region: __TEMPLATE_IAMBIC_AWS_REGION
      - name: invoke container
        id: run_container
        run: |
          while ! docker pull ${IMAGE} ; do sleep 3; done
          mkdir -p github_context
          mkdir -p data
          echo $GITHUB_CONTEXT > github_context/github_context.json
          docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION -e AWS_REGION=$AWS_REGION -v $(pwd)/github_context/:/root/github_context/ -v $(pwd)/data/:/root/data/ --entrypoint /bin/bash ${IMAGE} -c "python -m iambic.cicd.github"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          IMAGE: "public.ecr.aws/s2p9s3r8/iambic:latest"
      - name: Archive proosed_changes.yaml artifacts
        uses: actions/upload-artifact@v3
        with:
          name: data
          path: |
            data
