name: Run Iambic Detect
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'
jobs:
  iambic-import:
    runs-on: ubuntu-latest
    environment: production
    name: Detect Cloud and Google Environment changes
    timeout-minutes: 13 # this job is scheduled for every 15 min, setting it to 13 to have some margin
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      id-token: write
      contents: read
    steps:
      - name: trigger_workflow
        id: trigger_workflow
        run: |
          echo "trigger workflow"
