name: Run Iambic Import
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */4 * * *' # import at minute 0 past every 4th hour
jobs:
  iambic-import:
    runs-on: ubuntu-latest
    environment: production
    name: Import Cloud and Google Environment
    timeout-minutes: 60 # Setting this to 60 min for now. If this takes longer, it needs better performance improvement
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      id-token: write
      contents: read
    steps:
      - name: trigger_workflow
        id: trigger_workflow
        run: |
          echo "trigger workflow"
