extends:
  - key: AWS_SECRETS_MANAGER
    value: arn:aws:secretsmanager:us-west-2:759357822767:secret:dev/google-MmAS1o
    assume_role_arn: arn:aws:iam::759357822767:role/IambicSpokeRole
version: '1'
aws:
  organizations:
    - org_id: 'o-yfdp0r70sq'
      assume_role_arn: 'arn:aws:iam::259868150464:role/IambicSpokeRole'
      aws_profile: 'staging/staging_admin'
      org_name: 'staging'
      identity_center_account:
        account_id: '259868150464'
        region: 'us-east-1'
      account_rules:
        - included_accounts:
            - '*'
          enabled: true
        - included_accounts:
            - '969947703986'
            - '114567474685'
          enabled: false
      default_rule:
        enabled: true
  accounts:
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::759357822767:role/OrganizationAccountAccessRole
      account_id: '759357822767'
      org_id: o-yfdp0r70sq
      account_name: development
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::259868150464:role/OrganizationAccountAccessRole
      account_id: '259868150464'
      org_id: o-yfdp0r70sq
      account_name: staging
      role_access_tag: noq-authorized
      identity_center_details:
        region: us-east-1
        org_account_map:
          '420317713496': Noq Audit
          '306086318698': global_tenant_data_prod
          '894599878328': zelkova
          '869532243584': nonstandard_org_role
          '242350334841': test
          '940552945933': production
          '694815895589': demo-2
          '969947703986': '@!#!@#)(%*#R)QWITFGO)FG+=0984'
          '972417093400': demo-1
          '430422300865': Noq Log Archive
          '404594182786': ses
          '114567474685': space in account name
          '258300530029': global_prod_tenant_data
          '759357822767': development
          '259868150464': staging
          '518317429440': demo-3
          '197024362139': unusual_demo
          '775726381634': Cyberdyne Demo Org
          '350876197038': development-2
          '615395543222': global_tenant_data_staging
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::940552945933:role/OrganizationAccountAccessRole
      account_id: '940552945933'
      org_id: o-yfdp0r70sq
      account_name: production
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::420317713496:role/OrganizationAccountAccessRole
      account_id: '420317713496'
      org_id: o-yfdp0r70sq
      account_name: Noq Audit
      role_access_tag: noq-authorized
      variables:
        - key: environment
          value: prod
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::306086318698:role/OrganizationAccountAccessRole
      account_id: '306086318698'
      org_id: o-yfdp0r70sq
      account_name: global_tenant_data_prod
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::894599878328:role/OrganizationAccountAccessRole
      account_id: '894599878328'
      org_id: o-yfdp0r70sq
      account_name: zelkova
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::869532243584:role/OrganizationAccountAccessRole
      account_id: '869532243584'
      org_id: o-yfdp0r70sq
      account_name: nonstandard_org_role
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::242350334841:role/OrganizationAccountAccessRole
      account_id: '242350334841'
      org_id: o-yfdp0r70sq
      account_name: test
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::694815895589:role/OrganizationAccountAccessRole
      account_id: '694815895589'
      org_id: o-yfdp0r70sq
      account_name: demo-2
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::972417093400:role/OrganizationAccountAccessRole
      account_id: '972417093400'
      org_id: o-yfdp0r70sq
      account_name: demo-1
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::430422300865:role/OrganizationAccountAccessRole
      account_id: '430422300865'
      org_id: o-yfdp0r70sq
      account_name: Noq Log Archive
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::404594182786:role/OrganizationAccountAccessRole
      account_id: '404594182786'
      org_id: o-yfdp0r70sq
      account_name: ses
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::258300530029:role/OrganizationAccountAccessRole
      account_id: '258300530029'
      org_id: o-yfdp0r70sq
      account_name: global_prod_tenant_data
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::518317429440:role/OrganizationAccountAccessRole
      account_id: '518317429440'
      org_id: o-yfdp0r70sq
      account_name: demo-3
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::197024362139:role/OrganizationAccountAccessRole
      account_id: '197024362139'
      org_id: o-yfdp0r70sq
      account_name: unusual_demo
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::775726381634:role/OrganizationAccountAccessRole
      account_id: '775726381634'
      org_id: o-yfdp0r70sq
      account_name: Cyberdyne Demo Org
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::350876197038:role/OrganizationAccountAccessRole
      account_id: '350876197038'
      org_id: o-yfdp0r70sq
      account_name: development-2
      role_access_tag: noq-authorized
    - default_region: us-east-1
      assume_role_arn: arn:aws:iam::615395543222:role/OrganizationAccountAccessRole
      account_id: '615395543222'
      org_id: o-yfdp0r70sq
      account_name: global_tenant_data_staging
      role_access_tag: noq-authorized
google:
  groups:
    enabled: true

slack:
  alert_channel_id: 'C046KESSMQ8'

sqs_cloudtrail_changes_queues:
  - arn:aws:sqs:us-east-1:759357822767:noqform-iam-mutation-events
