accounts:
- account_id: '759357822767'
  account_name: Development
  aws_profile: noq_dev
- account_id: '259868150464'
  account_name: Staging
  aws_profile: noq_staging
- account_id: '940552945933'
  account_name: Production
  aws_profile: noq_prod
