extends:
  - key: AWS_SECRETS_MANAGER
    value: arn:aws:secretsmanager:us-west-2:759357822767:secret:dev/google-MmAS1o

accounts:
- account_id: '759357822767'
  account_name: Development
  aws_profile: noq_dev
- account_id: '259868150464'
  account_name: Staging
  aws_profile: noq_staging
- account_id: '940552945933'
  account_name: Production
  aws_profile: noq_prod

slack:
  alert_channel_id: 'C046KESSMQ8'

sqs:
  queues:
    iam_mutation: 
      arn: arn:aws:sqs:us-east-1:759357822767:noqform-iam-mutation-events
