name: Build container
# This builds the container upon a push event in noqdev/iambic repository
on:
  # Testing this is a pain in the rear.
  # One way to test is to enable event type pull_request; however, our setup
  # is restrictive on who can assume the container building role. You can consider
  # temporarily open the role to allow the pull_request or via specific branch to
  # do the image building in teh aws assume role side.
  # pull_request:
  push:
   branches:
     - main
jobs:
  build-container:
    if: ${{ github.repository == 'noqdev/iambic' && github.event.commits[0].author.name != 'Version Auto Bump' }}
    runs-on: self-hosted
    name: Build Container
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.VERSION_BUMP_TOKEN }}
      - name: bootstrap
        run: |
          python3.10 -m venv build-env
          . build-env/bin/activate && pip install poetry
      - name: set git identity
        run: |
          git config user.name "Version Auto Bump"
          git config user.email "github-action-version-auto-bump@noq.dev"
      - name: bump version
        id: bump-version
        run: |
          . build-env/bin/activate && python build_utils/tag_and_build_container.py bump-version
          git add pyproject.toml
          git commit -m "Bump version"
          git push origin HEAD:${BRANCH_NAME}
          git tag v$(python build_utils/tag_and_build_container.py print-current-version)
          git push --tags
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::759357822767:role/iambic_image_builder
          aws-region: us-east-1
      - name: build container
        id: build-container
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l1s5s8m2
          . build-env/bin/activate && make build_docker upload_docker