name: Build container
on:
  pull_request:
  push:
   branches:
     - main
jobs:
  build-container:
    runs-on: self-hosted
    name: Build Container
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: set git identity
        run: |
          git config user.name "Version Auto Bump"
          git config user.email "github-action-version-auto-bump@noq.dev"
      - name: bootstrap
        run: |
          python3.10 -m venv build-env
          . build-env/bin/activate && pip install poetry
      - name: bump version
        id: bump-version
        run: |
          . build-env/bin/activate && python build_utils/tag_and_build_container.py bump-version
          git add pyproject.toml
          git commit -m "Bump version"
          git push origin HEAD:${BRANCH_NAME}
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::759357822767:role/iambic_image_builder
          aws-region: us-east-1
      - name: build container
        id: build-container
        run: |
          . build-env/bin/activate && make build_docker upload_docker
