name: Publish Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    if: ${{ github.repository == 'noqdev/iambic' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      security-events: write
      statuses: write
      discussions: write
    steps:
    - name: bootstrap
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.37.3
    - uses: actions/checkout@v3
    - name: scan container
      id: scan-container
      run: |
        docker logout ghcr.io
        make trivy_scan
        make trivy_sbom
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: iambic.sbom.json
  build-n-publish:
    if: ${{ github.repository == 'noqdev/iambic' }}
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: bootstrap
      run: |
        pip install poetry setuptools pip --upgrade
    - run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
    - name: Publish package
      run: poetry publish --build